apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jvb
  name: jvb
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: jvb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jvb
    spec:
      containers:
      - env:
        - name: DOCKER_HOST_ADDRESS
          value: <..place the public IP address of any of the worker node here...>
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JVB_AUTH_PASSWORD
          value: password
        - name: JVB_AUTH_USER
          value: jvb
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: JVB_PORT
          value: "30000"
        - name: JVB_STUN_SERVERS
          value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
        - name: JVB_TCP_PORT
          value: "30001"
        - name: TZ
          value: Europe/Paris
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_SERVER
          value: prosody
        image: jitsi/jvb
        imagePullPolicy: Always
        name: jvb
        ports:
        - containerPort: 30000
          name: 30000udp02
          protocol: UDP
        - containerPort: 30001
          name: 30001tcp02
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
